### ISSUE TITLE
Support for Homey Energy

### ISSUE THREAD

**Issue by DiedB** [jordenc/nl.innovationinmotion.slide#3]
Homey recently added the Energy feature, allowing users to gain insight into the energy usage of their homes. Could the standby power consumption of Slide be added?

https://apps.developer.athom.com/tutorial-Drivers-Energy.html

If you'd like to add it, I can do some measurements on the power consumption of Slide.

**Comment by jordenc** [comment]
If you can measure it, I will add it to the app for sure!

**Comment by DiedB** [comment]
It seems to be hard to measure as its standby consumption is less than 1W (my power meter can't measure that). Can't find it in any data sheets either. Maybe someone else can measure it?

**Comment by jordenc** [comment]
I will add an update for a "constant usage" of 1 watt. I don't think it's possible to add a value less than 1 watt, but if that's possible and someone comes up with the correct usage I will make an update again.

**Comment by DiedB** [comment]
I don't think that's would be the best idea, as your estimate might be off by an order of magnitude. The Homey SDK definitely supports values less than 1W and it's better to not implement it than implementing a guesstimate.

**Comment by jordenc** [comment]
I have asked Innovation in Motion, the creators of Slide, if they know a more precise (gu)estimate.
