### ISSUE TITLE
Triggers not working

### ISSUE THREAD

**Issue by zeppie** [jordenc/nl.innovationinmotion.slide#4]
Hi, 
First of all thanks for the great app. 
Currently installing my second slide and a few issues.

Triggers not working if slide is opened/closed with google home, slide app or manual

**Comment by jordenc** [comment]
Just tried with version 0.4.2 and it now works.

Install through https://homey.app/nl-nl/app/nl.innovationinmotion.slide/Slide/test/ or wait a few days until Athom has approved the new version.
